export const mock = [
  {
    title: '27/12/2022',
    data: [
      {
        hour: '18:00',
        data: '27/12/2022',
        name: 'Coke and the rest, rest rest testing, testing',
        description: 'Sanduíche de pão integral com atum e salada de alface e tomate',
        type: 'on',
      },
      {
        hour: '19:00',
        data: '27/12/2022',
        name: 'Rice and beans',
        description: 'Comida padrão do Brasil, China e países asiáticos.',
        type: 'on',
      },
      {
        hour: '19:00',
        data: '27/12/2022',
        name: 'Burger',
        description: 'Lanche da tarde',
        type: 'on',
      },
      {
        hour: '19:30',
        data: '27/12/2022',
        name: 'Pizza',
        description: 'lanche da noite',
        type: 'on',
      },
    ],
  },
  {
    title: '26/12/2022',
    data: [
      {
        hour: '18:00',
        data: '26/12/2022',
        name: 'Coke and the rest, rest rest testing, testing',
        description: 'bolo de morango',
        type: 'on',
      },
      {
        hour: '19:00',
        data: '26/12/2022',
        name: 'Coke',
        description: 'bolo de chocolate',
        type: 'on',
      },
    ],
  },
  {
    title: '25/12/2022',
    data: [
      {
        hour: '18:00',
        data: '25/12/2022',
        name: 'Coke and the rest, rest rest testing, testing',
        description: 'bolo de morango',
        type: 'off',
      },
      {
        hour: '19:00',
        data: '25/12/2022',
        name: 'Coke',
        description: 'bolo de chocolate',
        type: 'off',
      },
      {
        hour: '20:00',
        data: '25/12/2022',
        name: 'Coke 2',
        description: 'bolo de morango',
        type: 'off',
      },
      {
        hour: '21:00',
        data: '25/12/2022',
        name: 'Coke 3',
        description: 'bolo de morango',
        type: 'off',
      },
      {
        hour: '22:00',
        data: '25/12/2022',
        name: 'Coke 4',
        description: 'bolo de morango',
        type: 'off',
      },
      {
        hour: '23:00',
        data: '25/12/2022',
        name: 'Coke 5',
        description: 'bolo de morango',
        type: 'off',
      },
      {
        hour: '23:50',
        data: '25/12/2022',
        name: 'Coke 6',
        description: 'bolo de morango',
        type: 'off',
      },
      {
        hour: '23:50',
        data: '25/12/2022',
        name: 'Coke 7',
        description: 'bolo de morango',
        type: 'on',
      },
    ],
  },
];
